clean_now:
  name: Clean Inactive Areas
  description: Manually trigger cleaning of inactive entertainment areas only

clean_all:
  name: Clean All Areas
  description: Clean all entertainment areas including active ones (use with caution!)
